In [3]:


def square(x):
    return x**2

In [4]:
a = int(input('The number = '))
print ('The square of {} is {}'.format(a , square(a)))

The number = 5
The square of 5 is 25


2. Write a function that takes 2 variable and obtain the summation and multiplacation 
   Then test the function by taking an input from a user (Repeat using LAMBDA Expressions)

In [2]:
def Sum_Multi(x,y):
    summation=x+y
    multiply=x*y
    return (summation,multiply)

In [4]:
a=int(input('Enter any integer = ') ) 
b=int(input('Enter another integer = ') ) 

result_sum , result_multi = Sum_Multi(a,b)

print ('Summation is  {} \nMultiplication is {}'.format(result_sum , result_multi))

Enter any integer = 5
Enter another integer = 6
Summation is  11 
Multiplication is 30


USING  LAMBDA....  EXPRESSIONS

In [1]:
a=int(input('Enter any integer = ') ) 
b=int(input('Enter another integer = ') ) 

summation = lambda x,y:x+y
multiply = lambda x,y:x*y

print('summation is {} \nmultiply is {}'.format(summation(a,b),multiply(a,b)))

Enter any integer = 6
Enter another integer = 7
summation is 13 
multiply is 42


 Q 3 . Write a funcation that takes a variable and returns it's FACTORIAL

In [1]:
def factorial(x):
    if x == 0:
        return 1
    return x*factorial(x-1)

In [2]:
a=int(input('Enter any integer = ') )

print ( 'Factorial if {} is {}'.format( a,factorial(a)))

Enter any integer = 4
Factorial if 4 is 24


Q4 . Develop a script whose items are squares of the orginal list 

In [3]:
my_list = range(1,21)

print ([x**2 for x in my_list])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


Q5 . Write a function that squares a variable and then test the function 
using a list of integer numbers RANGING from -20 to 20

In [1]:
def squared(x):
    return (x*x)

numbers = range (-20,20)

num_square = list(map(lambda x : squared(x) , numbers))

print ('The square of the list {} is {} '.format(numbers,num_square))

The square of the list range(-20, 20) is [400, 361, 324, 289, 256, 225, 196, 169, 144, 121, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1, 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361] 


Q6 . Write 3 functions that take RADIOUS of a CIRCULE and return the DIAMETER , AREA and CIRCUMFERENCE , test the function using an input form a user

In [18]:
import math 

def circule_dia(radius):
    return 2*radius

def circule_area(radius):
    return math.pi*radius**2

def circule_cir(radius):
    return 2*math.pi*radius

In [20]:
r = int(input('Enter a radius = '))

print('Circule Diameter = ',circule_dia(r))
print('Circule Area = ',circule_area(r))
print('Circule Circumference = ',circule_cir(r))

Enter a radius = 4
Circule Diameter =  8
Circule Area =  50.26548245743669
Circule Circumference =  25.132741228718345


Q7 . Write a code that takes a RANGE from a user ( Upper and Lower Bound )      and Returns a list of Positive and Even numders ONLY

In [2]:
bound_min = int(input('Enter a lower bound '))
bound_max = int(input('Enter a upper bound '))

numbers = range(bound_min,bound_max)

filtered_number = list(filter(lambda x: (x>0 and x%2==0) ,numbers))
print(filtered_number)

Enter a lower bound -30
Enter a upper bound 10
[2, 4, 6, 8]


Q8 . Using Filter and Lambda Expression , Write a code That takes a List of Numbers below and returns EVEN numbers only

In [4]:
numbers = [6,17,55,22,120,59,220,200,1]

even_numbers = list(filter(lambda x:(x%2==0),numbers))

print (even_numbers)

[6, 22, 120, 220, 200]


Q9 . Write a Function That Takes Two NUMPY Matrices and Return The ADDITION , SUBTRACTION ,TRANsPOSE ,PRODUCT ,DOT PRODUCT

In [21]:
def matrix_operation(a,b):
    print('Matrices addition = \n ',np.add(a,b))
    print('Matrices Subtract =  \n',np.subtract(a,b))
    print('Matrices multiply =  \n',np.multiply(a,b))
    print('Matrices Transpose =  \n',a.T)
    print('Matrices Transpose =  \n',b.T)
    print('Matrices DOT_MULTIPLi = \n ',np.dot(a,b))
    print('Matrices squre_rout = \n',np.sqrt(a))

In [22]:
import numpy as np

x = np.array([[3,9],
             [8,5]])

y = np.array([[2,3],
             [1,7]])

matrix_operation(x,y)


Matrices addition = 
  [[ 5 12]
 [ 9 12]]
Matrices Subtract =  
 [[ 1  6]
 [ 7 -2]]
Matrices multiply =  
 [[ 6 27]
 [ 8 35]]
Matrices Transpose =  
 [[3 8]
 [9 5]]
Matrices Transpose =  
 [[2 1]
 [3 7]]
Matrices DOT_MULTIPLi = 
  [[15 72]
 [21 59]]
Matrices squre_rout = 
 [[1.73205081 3.        ]
 [2.82842712 2.23606798]]
